version: "2"
services:

    ##########################################
    #      GCC
    ##########################################

    # gcc 7
    build_gcc_7:
        image: gcc:7.1.0
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && g++ -std=c++17 test/system_tests/containers.cpp"
            && g++ -std=c++17 test/system_tests/math.cpp"
            && g++ -std=c++17 test/system_tests/operators.cpp"
            && g++ -std=c++17 test/system_tests/type.cpp"

    # gcc 8
    build_gcc_8:
        image: gcc:8.1.0
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && g++ -std=c++17 test/system_tests/containers.cpp"
            && g++ -std=c++17 test/system_tests/math.cpp"
            && g++ -std=c++17 test/system_tests/operators.cpp"
            && g++ -std=c++17 test/system_tests/type.cpp"

    # gcc 9
    build_gcc_9:
        image: gcc:9.1.0
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && g++ -std=c++17 test/system_tests/containers.cpp"
            && g++ -std=c++17 test/system_tests/math.cpp"
            && g++ -std=c++17 test/system_tests/operators.cpp"
            && g++ -std=c++17 test/system_tests/type.cpp"

    # gcc 10
    build_gcc_10:
        image: gcc:10.1.0
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && g++ -std=c++17 test/system_tests/containers.cpp"
            && g++ -std=c++17 test/system_tests/math.cpp"
            && g++ -std=c++17 test/system_tests/operators.cpp"
            && g++ -std=c++17 test/system_tests/type.cpp"
            && g++ -std=c++20 test/system_tests/containers.cpp"
            && g++ -std=c++20 test/system_tests/math.cpp"
            && g++ -std=c++20 test/system_tests/operators.cpp"
            && g++ -std=c++20 test/system_tests/type.cpp"

    # gcc 11
    build_gcc_11:
        image: gcc:11.1.0
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && g++ -std=c++17 test/system_tests/containers.cpp"
            && g++ -std=c++17 test/system_tests/math.cpp"
            && g++ -std=c++17 test/system_tests/operators.cpp"
            && g++ -std=c++17 test/system_tests/type.cpp"
            && g++ -std=c++20 test/system_tests/containers.cpp"
            && g++ -std=c++20 test/system_tests/math.cpp"
            && g++ -std=c++20 test/system_tests/operators.cpp"
            && g++ -std=c++20 test/system_tests/type.cpp"

    # gcc 12
    build_gcc_12:
        image: gcc:12.1.0
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && g++ -std=c++17 test/system_tests/containers.cpp"
            && g++ -std=c++17 test/system_tests/math.cpp"
            && g++ -std=c++17 test/system_tests/operators.cpp"
            && g++ -std=c++17 test/system_tests/type.cpp"
            && g++ -std=c++20 test/system_tests/containers.cpp"
            && g++ -std=c++20 test/system_tests/math.cpp"
            && g++ -std=c++20 test/system_tests/operators.cpp"
            && g++ -std=c++20 test/system_tests/type.cpp"

    ##########################################
    #      CLANG
    ##########################################

    # clang 5
    build_clang_5:
        image: silkeh/clang:5
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"

    # clang 6
    build_clang_6:
        image: silkeh/clang:6
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"

    # clang 7
    build_clang_7:
        image: silkeh/clang:7
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"

    # clang 8
    build_clang_8:
        image: silkeh/clang:8
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"

    # clang 9
    build_clang_9:
        image: silkeh/clang:9
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"
            && clang++ -std=c++2a test/system_tests/containers.cpp"
            && clang++ -std=c++2a test/system_tests/math.cpp"
            && clang++ -std=c++2a test/system_tests/operators.cpp"
            && clang++ -std=c++2a test/system_tests/type.cpp"

    # clang 10
    build_clang_10:
        image: silkeh/clang:10
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"
            && clang++ -std=c++2a test/system_tests/containers.cpp"
            && clang++ -std=c++2a test/system_tests/math.cpp"
            && clang++ -std=c++2a test/system_tests/operators.cpp"
            && clang++ -std=c++2a test/system_tests/type.cpp"

    # clang 11
    build_clang_11:
        image: silkeh/clang:11
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"
            && clang++ -std=c++2a test/system_tests/containers.cpp"
            && clang++ -std=c++2a test/system_tests/math.cpp"
            && clang++ -std=c++2a test/system_tests/operators.cpp"
            && clang++ -std=c++2a test/system_tests/type.cpp"

    # clang 12
    build_clang_12:
        image: silkeh/clang:12
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"
            && clang++ -std=c++2a test/system_tests/containers.cpp"
            && clang++ -std=c++2a test/system_tests/math.cpp"
            && clang++ -std=c++2a test/system_tests/operators.cpp"
            && clang++ -std=c++2a test/system_tests/type.cpp"

    # clang 13
    build_clang_13:
        image: silkeh/clang:13
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"
            && clang++ -std=c++2a test/system_tests/containers.cpp"
            && clang++ -std=c++2a test/system_tests/math.cpp"
            && clang++ -std=c++2a test/system_tests/operators.cpp"
            && clang++ -std=c++2a test/system_tests/type.cpp"

    # clang 14
    build_clang_14:
        image: silkeh/clang:14
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && mkdir -p /usr/include/include
            && cp -r include/* /usr/include/include
            && clang++ -std=c++17 test/system_tests/containers.cpp"
            && clang++ -std=c++17 test/system_tests/math.cpp"
            && clang++ -std=c++17 test/system_tests/operators.cpp"
            && clang++ -std=c++17 test/system_tests/type.cpp"
            && clang++ -std=c++2a test/system_tests/containers.cpp"
            && clang++ -std=c++2a test/system_tests/math.cpp"
            && clang++ -std=c++2a test/system_tests/operators.cpp"
            && clang++ -std=c++2a test/system_tests/type.cpp"